### ISSUE TITLE
--bug-report will result in poxy experiencing repetitive self-invocation

### ISSUE THREAD

**Issue by wroyca** [marzer/poxy#29]
## Environment

**version and/or commit hash:**

0.13.4

## Describe the bug

--bug-report will result in poxy experiencing repetitive self-invocation, where removing --bug-report from its children does not appear to take place.

```bash
C:\Users\wroy\Desktop\echo\doc>poxy --bug-report
Preparing output paths
Invoking poxy
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\wroy\AppData\Local\Programs\Python\Python311\Scripts\poxy.exe\__main__.py", line 7, in <module>
  File "C:\Users\wroy\AppData\Local\Programs\Python\Python311\Lib\site-packages\poxy\main.py", line 74, in main
    _invoker(main, invoker=False)
  File "C:\Users\wroy\AppData\Local\Programs\Python\Python311\Lib\site-packages\poxy\main.py", line 26, in _invoker
    func(**kwargs)
  File "C:\Users\wroy\AppData\Local\Programs\Python\Python311\Lib\site-packages\poxy\main.py", line 239, in main
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "C:\Users\wroy\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wroy\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1196, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 319, in decode
KeyboardInterrupt
^C
```

![image](https://github.com/marzer/poxy/assets/91024200/8080e69f-b427-4d77-b8ae-20c57a5c99a4)

**Comment by marzer** [comment]
lmao. "but who watches the watchmen?"
