### ISSUE TITLE
Cannot run poxy on Ubuntu 24.04

### ISSUE THREAD

**Issue by dekinet** [marzer/poxy#38]
## Environment

- Ubuntu 24.04
- python 3.12.3
- poxy 0.19.0

## Describe the bug

poxy installs OK, but I cannot get it to run, with the error being: `ModuleNotFoundError: No module named 'distutils'`. I cannot find any successful way to install distutils on Ubuntu 24.04 - it seems it has been deprecated.

Am I doing something wrong, or does poxy need to be updated to remove a dependency on distutils?
Would really appreciate some pointers if I'm installing/running it incorrectly.

## Additional information

I have successfully installed/run poxy on Ubuntu 20.04.

I tried replicating the setup that's working on 20.04 on 24.04:
- Installed Miniconda
- Set up conda virtual environment and ran `pip install poxy`
- As far as I remember, this "just worked" on Ubuntu 20.04
- I get the ModuleNotFoundError mentioned above on Ununtu 24.04

I tried creating a (non-Miniconda) python virtual environment (path at ~/.venv/docs):
- `~/.venv/docs/bin/pip install poxy` works fine
- Running `~/.venv/docs/bin/poxy` results in the same ModuleNotFoundError.

Attempting to install distutils:
```
$ ~/.venv/docs/bin/pip install distutils
ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
ERROR: No matching distribution found for distutils
```

## `--bug-report`

-   [ ] I have attached the zip file generated when using the --bug-report option
Not attached, I cannot get poxy to run to generate the bug report.

**Comment by marzer** [comment]
> Am I doing something wrong, or does poxy need to be updated to remove a dependency on distutils?

Nope, you're not doing anything wrong. Looks like I need to do a pass over the dependencies. Thanks for letting me know :)

**Comment by marzer** [comment]
Looking into this now. Poxy uses setuptools+wheels for pypi packaging, and [this issue](https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-installed) suggests that having setuptools should satisfy that machinery. Can you try installing that instead?

Alternatively, it may be that some dependency I'm relying on transitively uses `distutils`, which would be a pain. I'd have to look into that.

**Comment by marzer** [comment]
Also, if there's a call stack accompanying the `ModuleNotFoundError`, please post it.

**Comment by dekinet** [comment]
> Also, if there's a call stack accompanying the `ModuleNotFoundError`, please post it.

Sorry, should have included that:

```
$ poxy
Traceback (most recent call last):
  File "/home/me/.local/bin/poxy", line 5, in <module>
    from poxy import main
  File "/home/me/.local/share/pipx/venvs/poxy/lib/python3.12/site-packages/poxy/__init__.py", line 7, in <module>
    from .main import main, main_blog_post
  File "/home/me/.local/share/pipx/venvs/poxy/lib/python3.12/site-packages/poxy/main.py", line 24, in <module>
    from .run import run
  File "/home/me/.local/share/pipx/venvs/poxy/lib/python3.12/site-packages/poxy/run.py", line 15, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'
```

**Comment by dekinet** [comment]
> Looking into this now. Poxy uses setuptools+wheels for pypi packaging, and [this issue](https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-installed) suggests that having setuptools should satisfy that machinery in python 3.12. Can you try installing that instead?
> 
> Alternatively, it may be that some dependency I'm relying on transitively uses `distutils`, which would be a pain. I'd have to look into that.

I have to say I'm a bit out of my depth with package management in python. However, I've attempted to install setuptools:

```
$ /home/me/.local/share/pipx/shared/bin/pip list
Package    Version
---------- -------
pip        24.3.1
setuptools 75.2.0
```

The result is still the same:

```
$ ~/.local/share/pipx/venvs/poxy/bin/poxy
Traceback (most recent call last):
  File "/home/me/.local/share/pipx/venvs/poxy/bin/poxy", line 5, in <module>
    from poxy import main
  File "/home/me/.local/share/pipx/venvs/poxy/lib/python3.12/site-packages/poxy/__init__.py", line 7, in <module>
    from .main import main, main_blog_post
  File "/home/me/.local/share/pipx/venvs/poxy/lib/python3.12/site-packages/poxy/main.py", line 24, in <module>
    from .run import run
  File "/home/me/.local/share/pipx/venvs/poxy/lib/python3.12/site-packages/poxy/run.py", line 15, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'
```

**Comment by marzer** [comment]
Ah! `from distutils.dir_util import copy_tree` is instructive. Looks like I'm using a version of `copy_tree` that's from the deprecated module, rather than using the one in `shutil`. Alrighty, that's easy fixed. I'll take care of that later today.

**Comment by marzer** [comment]
Should be fixed in 0.19.1. Thanks for the report 😄

**Comment by dekinet** [comment]
Awesome - works fine now. Thanks for the quick turnaround.
